language: node_js
node_js:
- '0.10'
before_install:
- gem install sass
- npm install -g grunt-cli
- npm install -g bower
- bower install
script: npm run travis
env:
  global:
    secure: EPX+NUuZXxM+IDYhgY1sy1Ruc9uCzvnrIpa/XqTS1FciWrjMP36y6oUu4xMxwbcsapYOd4cgwygprXE8xjQBuI+hKHTmbjHsZQhjvbyZ/XD3ZK0sOVC4SWjCGk5PTuMsGIUqU03oc19OTH6brFWgQJ2cxZ7jtI0Oy64w5PTI8Gk=
